name: Testing-CI/CD

on:
 push:
   branches:
     - test-branch

env:
 DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
 DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
 DOCKER_REPO: ${{ secrets.DOCKER_REPO }}
 
jobs:
 Build-Deploy:
   runs-on: ubuntu-latest

   steps:
     - name: Checkout
       uses: actions/checkout@v2


     - name: Set up Docker
       uses: docker/setup-buildx-action@v1

     - name: Login to Docker Hub
       uses: docker/login-action@v3
       with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

     - name: Retrieve Latest Docker Tag
       id: latest_tag
       run: |
           echo "Retrieving latest tag for $DOCKER_USERNAME/$DOCKER_REPO..."

           latest_tag=$(curl -s -H "Authorization: Bearer $DOCKER_PASSWORD" \
            https://hub.docker.com/v2/repositories/$DOCKER_USERNAME/$DOCKER_REPO/tags?page_size=100 \
            | jq -r '[.results[].name | select(test("^v[0-9]+$")) | ltrimstr("v") | tonumber] | max')

           if [ "$latest_tag" = "null" ]; then
            latest_tag=0
           fi

           echo "latest_tag=v$latest_tag"
           echo "latest_tag=v$latest_tag" >> $GITHUB_OUTPUT

     - name: Increment Version Number
       id: increment_version
       run: |
         latest_tag=${{ steps.latest_tag.outputs.latest_tag }}
         number=$(echo "$latest_tag" | grep -oE '[0-9]+$')
         if [ -z "$number" ]; then
          number=0
         fi
         new_number=$((number + 1))
         new_version="v$new_number"
         echo "New version: $new_version"
         echo "::set-output name=new_version::$new_version"


     - name: Create Logs Directory
       run: |
         mkdir -p logs/fgv-logger
         cd logs/fgv-logger
         touch access.log error.log
    
     - name: Build Docker Image
       run: docker build -t $DOCKER_USERNAME/$DOCKER_REPO:${{ steps.increment_version.outputs.new_version }} .


     - name: Push Docker Image
       run: docker push $DOCKER_USERNAME/$DOCKER_REPO:${{ steps.increment_version.outputs.new_version }}
